---
# Tasks that will configure openntpd.

- name: ensure openntpd is at the latest version
  apt: name=openntpd state=latest

- name: ensure openntpd is started
  service: name=openntpd state=started enabled=yes
