---
# Tasks that will configure unattended upgrades.

- name: ensure unattended-upgrades is at the latest version
  apt: name=unattended-upgrades state=latest

- name: create periodic configuration
  template: >
    src=periodic.j2 dest=/etc/apt/apt.conf.d/10periodic
    owner=root group=root mode=0644

- name: create unattended-upgrades configuration
  template: >
    src=upgrades.j2 dest=/etc/apt/apt.conf.d/50unattended-upgrades
    owner=root group=root mode=0644
